version: "3.9"

services:
  api:
    build:
      context: ./app/api
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      - db
    volumes:
      - ./app/api:/app
  
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: